name: Update Flights Embed

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth requests

      - name: Run updater
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FLIGHT_CHANNEL_ID: ${{ secrets.FLIGHT_CHANNEL_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          FLIGHT_SHEET: travelDestinations
        run: |
          python bot.py
