name: Update Flights Embed

# Run on a schedule AND allow manual runs
on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth requests

      # Step 4: Run the updater
      - name: Run flights updater
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FLIGHT_CHANNEL_ID: ${{ secrets.FLIGHT_CHANNEL_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          FLIGHT_SHEET: travelDestinations
        run: |
          python bot.py
